import './globals.css';
import Header from './components/header/header';

export const metadata = {
  title: 'Append',
  description: 'Generated by create next app',
  icons: {
    icon: '../public/append-logo.png',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-none">
        <Header />
        {children}
      </body>
    </html>
  )
}
